using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using EngineLayer;
using FlashLFQ;
using GuiFunctions;
using IO.MzML;
using MassSpectrometry;
using MzLibSpectralAveraging;
using NUnit.Framework;
using SpectralAveraging;
using TaskLayer;

namespace Test
{
    [ExcludeFromCodeCoverage]
    public static class AveragingTests
    {
        private static string TestFolder;
        private static CommonParameters commonParameters;

        [OneTimeSetUp]
        public static void OneTimeSetUp()
        {
            TestFolder = Path.Combine(TestContext.CurrentContext.TestDirectory, @"AveragingTest");
            Directory.CreateDirectory(TestFolder);

            commonParameters = new CommonParameters(
                taskDescriptor: "AveragingTask",
                dissociationType: DissociationType.LowCID,
                maxThreadsToUsePerFile: 2);
        }

        [OneTimeTearDown]
        public static void OneTimeTearDown()
        {
            Directory.Delete(TestFolder, true);
        }

        [Test]
        public static void TestAveragingAllScans()
        {
            // load in everything necessary
            string spectraFile = Path.Combine(TestContext.CurrentContext.TestDirectory, @"TestData\sliced_b6.mzML");
            string testPath = Path.Combine(TestFolder, "TestAveragingAll");
            Directory.CreateDirectory(testPath);

            MzLibSpectralAveragingOptions options = new MzLibSpectralAveragingOptions()
            {
                SpectraFileProcessingType = SpectraFileProcessingType.AverageAll,
            };
            SpectralAveragingTask averagingTask = new(options) {CommonParameters = commonParameters};

            // run the averaging task
            var results = averagingTask.RunTask(testPath, new List<DbForTask>(), 
                new List<string>() { spectraFile }, "Task1-AveragingTask");

            // check results object
            Assert.That(results.NewSpectra.Count == 1);
            Assert.That(results.NewSpectra.Contains(Path.Combine(testPath, "sliced_b6-averaged.mzML")));
            Assert.That(results.NewDatabases == null);

            // check if all outputs exist
            Assert.That(File.Exists(Path.Combine(testPath, "AutoGeneratedManuscriptProse.txt")));
            Assert.That(File.Exists(Path.Combine(testPath, "results.txt")));
            Assert.That(File.Exists(Path.Combine(testPath, "sliced_b6-averaged.mzML")));
            Assert.That(File.Exists(Path.Combine(testPath, "sliced_b6-averaged.toml")));
            Assert.That(Directory.Exists(Path.Combine(TestFolder, "Task Settings")));
            Assert.That(File.Exists(Path.Combine(TestFolder, "Task Settings", "Task1-AveragingTaskconfig.toml")));

            // ensure averaged is only one scan
            var averagedScan = Mzml.LoadAllStaticData(Path.Combine(testPath, "sliced_b6-averaged.mzML")).GetAllScansList();
            Assert.That(averagedScan.Count, Is.EqualTo(1));

            Directory.Delete(testPath, true);
            Directory.Delete(Path.Combine(TestFolder, "Task Settings"), true);
        }

        [Test]
        public static void TestAveragingEveryNScans()
        {
            // load in everything necessary
            string spectraFile = Path.Combine(TestContext.CurrentContext.TestDirectory,
                @"TestData\SmallCalibratible_Yeast.mzML");
            string testPath = Path.Combine(TestFolder, "TestAveragingEveryNScans");
            Directory.CreateDirectory(testPath);

            MzLibSpectralAveragingOptions options = new MzLibSpectralAveragingOptions()
            {
                SpectraFileProcessingType = SpectraFileProcessingType.AverageEverynScans,
                NumberOfScansToAverage = 5,
            };
            SpectralAveragingTask averagingTask = new(options) { CommonParameters = commonParameters };

            // run the averaging task
            var results = averagingTask.RunTask(testPath, new List<DbForTask>(),
                new List<string>() { spectraFile }, "Task1-AveragingTask");

            // check results object
            Assert.That(results.NewSpectra.Count == 1);
            Assert.That(results.NewSpectra.Contains(Path.Combine(testPath, "SmallCalibratible_Yeast-averaged.mzML")));
            Assert.That(results.NewDatabases == null);

            // check if all outputs exist
            Assert.That(File.Exists(Path.Combine(testPath, "AutoGeneratedManuscriptProse.txt")));
            Assert.That(File.Exists(Path.Combine(testPath, "results.txt")));
            Assert.That(File.Exists(Path.Combine(testPath, "SmallCalibratible_Yeast-averaged.mzML")));
            Assert.That(File.Exists(Path.Combine(testPath, "SmallCalibratible_Yeast-averaged.toml")));
            Assert.That(Directory.Exists(Path.Combine(TestFolder, "Task Settings")));
            Assert.That(File.Exists(Path.Combine(TestFolder, "Task Settings", "Task1-AveragingTaskconfig.toml")));

            // ensure averaged every 5 scans
            var originalScans = Mzml.LoadAllStaticData(spectraFile).GetAllScansList();
            var averagedScans = Mzml.LoadAllStaticData(Path.Combine(testPath, "SmallCalibratible_Yeast-averaged.mzML")).GetAllScansList();
            Assert.That(originalScans.Count / 5 == averagedScans.Count);

            Directory.Delete(testPath, true);
            Directory.Delete(Path.Combine(TestFolder, "Task Settings"), true);
        }

        [Test]
        public static void TestAveragingDDAScans()
        {
            // load in everything necessary
            string spectraFile = Path.Combine(TestContext.CurrentContext.TestDirectory,
                @"TestData\SmallCalibratible_Yeast.mzML");
            string testPath = Path.Combine(TestFolder, "TestAveragingDDAScans");
            Directory.CreateDirectory(testPath);

            MzLibSpectralAveragingOptions options = new MzLibSpectralAveragingOptions()
            {
                SpectraFileProcessingType = SpectraFileProcessingType.AverageDDAScans,
                NumberOfScansToAverage = 5,
            };
            SpectralAveragingTask averagingTask = new(options) { CommonParameters = commonParameters };

            // run the averaging task
            var results = averagingTask.RunTask(testPath, new List<DbForTask>(),
                new List<string>() { spectraFile }, "Task1-AveragingTask");

            // check results object
            Assert.That(results.NewSpectra.Count == 1);
            Assert.That(results.NewSpectra.Contains(Path.Combine(testPath, "SmallCalibratible_Yeast-averaged.mzML")));
            Assert.That(results.NewDatabases == null);

            // check if all outputs exist
            Assert.That(File.Exists(Path.Combine(testPath, "AutoGeneratedManuscriptProse.txt")));
            Assert.That(File.Exists(Path.Combine(testPath, "results.txt")));
            Assert.That(File.Exists(Path.Combine(testPath, "SmallCalibratible_Yeast-averaged.mzML")));
            Assert.That(File.Exists(Path.Combine(testPath, "SmallCalibratible_Yeast-averaged.toml")));
            Assert.That(Directory.Exists(Path.Combine(TestFolder, "Task Settings")));
            Assert.That(File.Exists(Path.Combine(TestFolder, "Task Settings", "Task1-AveragingTaskconfig.toml")));

            // ensure averaged properly
            var originalFiles = Mzml.LoadAllStaticData(spectraFile);
            var averagedFiles = Mzml.LoadAllStaticData(Path.Combine(testPath, "SmallCalibratible_Yeast-averaged.mzML"));
            var originalMs1Scans = originalFiles.GetMS1Scans().ToList();
            var averagedMs1Scans = averagedFiles.GetMS1Scans().ToList();
            var originalMs2Scans = originalFiles.GetAllScansList().Where(p => p.MsnOrder == 2).ToList();
            var averagedMs2Scans = averagedFiles.GetAllScansList().Where(p => p.MsnOrder == 2).ToList();

            Assert.That(originalMs1Scans.Count / 5 == averagedMs1Scans.Count);
            for (var i = 0; i < averagedMs2Scans.Count; i++)
            {
                Assert.That(originalMs2Scans[i].MassSpectrum.Equals(averagedMs2Scans[i].MassSpectrum));
            }

            Directory.Delete(testPath, true);
            Directory.Delete(Path.Combine(TestFolder, "Task Settings"), true);
        }

        [Test]
        public static void TestExperimentalDesign()
        {
            // load in everything necessary
            string spectraFile = Path.Combine(TestContext.CurrentContext.TestDirectory,
                @"TestData\SmallCalibratible_Yeast.mzML");
            string testPath = Path.Combine(TestFolder, "TestAveragingExperimentalDesign");
            Directory.CreateDirectory(testPath);
            string myDatabase = Path.Combine(TestContext.CurrentContext.TestDirectory, @"TestData\smalldb.fasta");
            MzLibSpectralAveragingOptions options = new MzLibSpectralAveragingOptions()
            {
                SpectraFileProcessingType = SpectraFileProcessingType.AverageDDAScans,
                NumberOfScansToAverage = 5,
            };
            SpectralAveragingTask averagingTask = new(options) { CommonParameters = commonParameters };
            SearchTask searchTask = new SearchTask();

            // run the tasks
            EverythingRunnerEngine everythingRunnerEngine = new EverythingRunnerEngine(
                new List<(string, MetaMorpheusTask)> { ("Task1-Average", averagingTask), ("Task2-Search", searchTask) },
                new List<string> { spectraFile },
                new List<DbForTask> { new DbForTask(myDatabase, false) },
                testPath);

            // set up original experimental design (input to calibration)
            SpectraFileInfo fileInfo = new SpectraFileInfo(spectraFile, "condition", 0, 0, 0);
            var experimentalDesignFilePath = ExperimentalDesign.WriteExperimentalDesignToFile(new List<SpectraFileInfo> { fileInfo });

            everythingRunnerEngine.Run();

            // make sure everything is there
            Assert.That(File.Exists(Path.Combine(testPath, "allResults.txt")));

            Assert.That(Directory.Exists(Path.Combine(testPath, "Task Settings")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task Settings", "Task1-Averageconfig.toml")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task Settings", "Task2-Searchconfig.toml")));

            Assert.That(Directory.Exists(Path.Combine(testPath, "Task1-Average")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task1-Average", "AutoGeneratedManuscriptProse.txt")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task1-Average", "results.txt")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task1-Average", "SmallCalibratible_Yeast-averaged.mzML")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task1-Average", "SmallCalibratible_Yeast-averaged.toml")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task1-Average", "ExperimentalDesign.tsv")));

            Assert.That(Directory.Exists(Path.Combine(testPath, "Task2-Search")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task2-Search", "AutoGeneratedManuscriptProse.txt")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task2-Search", "results.txt")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task2-Search", "AllPeptides.psmtsv")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task2-Search", "AllPSMs.psmtsv")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task2-Search", "AllPSMs_FormattedForPercolator.tab")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task2-Search", "AllQuantifiedPeaks.tsv")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task2-Search", "AllQuantifiedPeptides.tsv")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task2-Search", "AllQuantifiedProteinGroups.tsv")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task2-Search", "SmallCalibratible_Yeast-averaged.mzID")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task2-Search", "ExperimentalDesign.tsv")));

            Directory.Delete(testPath, true);
        }

        [Test]
        public static void TestAveragingWithOtherTasks()
        {
            // load in everything necessary
            string spectraFile = Path.Combine(TestContext.CurrentContext.TestDirectory,
                @"TestData\SmallCalibratible_Yeast.mzML");
            string testPath = Path.Combine(TestFolder, "TestAveragingWithOtherTasks");
            string myDatabase = Path.Combine(TestContext.CurrentContext.TestDirectory, @"TestData\smalldb.fasta");
            Directory.CreateDirectory(testPath);

            MzLibSpectralAveragingOptions options = new MzLibSpectralAveragingOptions()
            {
                SpectraFileProcessingType = SpectraFileProcessingType.AverageDDAScans,
                NumberOfScansToAverage = 5,
            };
            SpectralAveragingTask averagingTask = new() { CommonParameters = commonParameters };
            averagingTask.GetType().GetProperty("Options")?.SetValue(averagingTask, options);
            CalibrationTask calibrationTask = new CalibrationTask();
            SearchTask searchTask = new SearchTask();

            // run the tasks
            EverythingRunnerEngine everythingRunnerEngine = new EverythingRunnerEngine(
                new List<(string, MetaMorpheusTask)>
                {
                    ("Task1-Calib", calibrationTask), ("Task2-Average", averagingTask), ("Task3-Search", searchTask)
                }, 
                new List<string> { spectraFile }, 
                new List<DbForTask> { new DbForTask(myDatabase, false) }, testPath);
            everythingRunnerEngine.Run();

            // make sure everything is there
            Assert.That(File.Exists(Path.Combine(testPath, "allResults.txt")));

            Assert.That(Directory.Exists(Path.Combine(testPath, "Task Settings")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task Settings", "Task1-Calibconfig.toml")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task Settings", "Task2-Averageconfig.toml")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task Settings", "Task3-Searchconfig.toml")));

            Assert.That(Directory.Exists(Path.Combine(testPath, "Task1-Calib")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task1-Calib", "AutoGeneratedManuscriptProse.txt")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task1-Calib", "results.txt")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task1-Calib", "SmallCalibratible_Yeast-calib.mzML")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task1-Calib", "SmallCalibratible_Yeast-calib.toml")));

            Assert.That(Directory.Exists(Path.Combine(testPath, "Task2-Average")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task2-Average", "AutoGeneratedManuscriptProse.txt")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task2-Average", "results.txt")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task2-Average", "SmallCalibratible_Yeast-calib-averaged.mzML")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task2-Average", "SmallCalibratible_Yeast-calib-averaged.toml")));

            Assert.That(Directory.Exists(Path.Combine(testPath, "Task3-Search")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task3-Search", "AutoGeneratedManuscriptProse.txt")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task3-Search", "results.txt")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task3-Search", "AllPeptides.psmtsv")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task3-Search", "AllPSMs.psmtsv")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task3-Search", "AllPSMs_FormattedForPercolator.tab")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task3-Search", "AllQuantifiedPeaks.tsv")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task3-Search", "AllQuantifiedPeptides.tsv")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task3-Search", "AllQuantifiedProteinGroups.tsv")));
            Assert.That(File.Exists(Path.Combine(testPath, "Task3-Search", "SmallCalibratible_Yeast-calib-averaged.mzID")));

            // ensure averaged properly
            var calibratedFiles = Mzml.LoadAllStaticData(Path.Combine(testPath, "Task1-Calib", "SmallCalibratible_Yeast-calib.mzML"));
            var averagedFiles = Mzml.LoadAllStaticData(Path.Combine(testPath, "Task2-Average", "SmallCalibratible_Yeast-calib-averaged.mzML"));
            var calibratedMs1Scans = calibratedFiles.GetMS1Scans().ToList();
            var averagedMs1Scans = averagedFiles.GetMS1Scans().ToList();
            var calibratedMs2Scans = calibratedFiles.GetAllScansList().Where(p => p.MsnOrder == 2).ToList();
            var averagedMs2Scans = averagedFiles.GetAllScansList().Where(p => p.MsnOrder == 2).ToList();

            Assert.That(calibratedMs1Scans.Count / 5 == averagedMs1Scans.Count);
            for (var i = 0; i < averagedMs2Scans.Count; i++)
            {
                Assert.That(calibratedMs2Scans[i].MassSpectrum.Equals(averagedMs2Scans[i].MassSpectrum));
            }

            Directory.Delete(testPath, true);
        }

        [Test]
        public static void TestMzLibSpecAveragingOptionsConstructor()
        {
            SpectralAveragingOptions specOptions = new SpectralAveragingOptions()
                { Percentile = 2, MinSigmaValue = 1.3, MaxSigmaValue = 3 };
            MzLibSpectralAveragingOptions options = new MzLibSpectralAveragingOptions(specOptions);
            MzLibAveragingOptionsViewModel optionsVM = new(options);
            Assert.That(optionsVM.RejectionType == RejectionType.NoRejection);
            Assert.That(optionsVM.WeightingType == WeightingType.NoWeight);
            Assert.That(optionsVM.SpectraFileProcessingType == SpectraFileProcessingType.AverageAll);
            Assert.That(optionsVM.PerformNormalization == true);
            Assert.That(optionsVM.OutputType == OutputType.mzML);
            Assert.That(optionsVM.ScanOverlap == 2);
            Assert.That(optionsVM.NumberOfScansToAverage == 5);
            Assert.That(Math.Abs(optionsVM.BinSize - 0.01) < 0.0001);
            Assert.That(Math.Abs(optionsVM.MinSigmaVale - 1.3) < 0.0001);
            Assert.That(Math.Abs(optionsVM.MaxSigmaValue - 3) < 0.0001);
            Assert.That(Math.Abs(optionsVM.Percentile - 2) < 0.0001);
            Assert.That(optionsVM.Name == "Default Options");
            Assert.That(optionsVM.SavedPath == null);
            Assert.That(optionsVM.OutputTypes.SequenceEqual(Enum.GetValues<OutputType>()));
            Assert.That(optionsVM.RejectionTypes.SequenceEqual(Enum.GetValues<RejectionType>().Where(p => p != RejectionType.Thermo).ToArray()));
            Assert.That(optionsVM.WeightingTypes.SequenceEqual(Enum.GetValues<WeightingType>()));
            Assert.That(optionsVM.SpectraFileProcessingTypes.SequenceEqual(Enum.GetValues<SpectraFileProcessingType>()));
        }

        [Test]
        public static void TestMzLibSpecAveragingOptionsResetDefaults()
        {
            // set all values
            SpectralAveragingOptions specOptions = new SpectralAveragingOptions()
                { Percentile = 2, MinSigmaValue = 1.3, MaxSigmaValue = 3 };
            MzLibSpectralAveragingOptions options = new MzLibSpectralAveragingOptions(specOptions);
            MzLibAveragingOptionsViewModel optionsVM = new(options);
            optionsVM.MzLibSpectralAveragingOptions = new MzLibSpectralAveragingOptions(specOptions);
            optionsVM.RejectionType = RejectionType.AveragedSigmaClipping;
            optionsVM.WeightingType = WeightingType.CauchyDistribution;
            optionsVM.SpectraFileProcessingType = SpectraFileProcessingType.AverageDDAScansWithOverlap;
            optionsVM.PerformNormalization = false;
            optionsVM.Percentile = 14;
            optionsVM.MinSigmaVale = 20;
            optionsVM.MaxSigmaValue = 15;
            optionsVM.BinSize = 4;
            optionsVM.NumberOfScansToAverage = 20;
            optionsVM.OutputType = OutputType.txt;
            optionsVM.ScanOverlap = 10;

            // ensure they were set
            Assert.That(Math.Abs(optionsVM.Percentile - 14) < 0.0001);
            Assert.That(optionsVM.RejectionType == RejectionType.AveragedSigmaClipping);
            Assert.That(optionsVM.WeightingType == WeightingType.CauchyDistribution);
            Assert.That(optionsVM.SpectraFileProcessingType == SpectraFileProcessingType.AverageDDAScansWithOverlap);
            Assert.That(optionsVM.PerformNormalization == false);
            Assert.That(optionsVM.OutputType == OutputType.txt);
            Assert.That(optionsVM.ScanOverlap == 10);
            Assert.That(optionsVM.NumberOfScansToAverage == 20);
            Assert.That(Math.Abs(optionsVM.BinSize - 4) < 0.0001);
            Assert.That(Math.Abs(optionsVM.MinSigmaVale - 20) < 0.0001);
            Assert.That(Math.Abs(optionsVM.MaxSigmaValue - 15) < 0.0001);
            Assert.That(optionsVM.Name == "Default Options");
            Assert.That(optionsVM.SavedPath == null);

            // reset all values and ensure they were set
            optionsVM.ResetDefaults();
            Assert.That(Math.Abs(optionsVM.Percentile - 0.1) < 0.0001);
            Assert.That(optionsVM.RejectionType == RejectionType.NoRejection);
            Assert.That(optionsVM.WeightingType == WeightingType.NoWeight);
            Assert.That(optionsVM.SpectraFileProcessingType == SpectraFileProcessingType.AverageAll);
            Assert.That(optionsVM.PerformNormalization == true);
            Assert.That(optionsVM.OutputType == OutputType.mzML);
            Assert.That(optionsVM.ScanOverlap == 2);
            Assert.That(optionsVM.NumberOfScansToAverage == 5);
            Assert.That(Math.Abs(optionsVM.BinSize - 0.01) < 0.0001);
            Assert.That(Math.Abs(optionsVM.MinSigmaVale - 1.5) < 0.0001);
            Assert.That(Math.Abs(optionsVM.MaxSigmaValue - 1.5) < 0.0001);
            Assert.That(optionsVM.Name == "Default Options");
            Assert.That(optionsVM.SavedPath == null);
            Assert.That(optionsVM.OutputTypes.SequenceEqual(Enum.GetValues<OutputType>()));
            Assert.That(optionsVM.RejectionTypes.SequenceEqual(Enum.GetValues<RejectionType>().Where(p => p != RejectionType.Thermo).ToArray()));
            Assert.That(optionsVM.WeightingTypes.SequenceEqual(Enum.GetValues<WeightingType>()));
            Assert.That(optionsVM.SpectraFileProcessingTypes.SequenceEqual(Enum.GetValues<SpectraFileProcessingType>()));
        }

        [Test]
        public static void TestMzLibSpectralAveragingOptionsSpecialGettersAndSetters()
        {
            SpectralAveragingOptions specOptions = new SpectralAveragingOptions()
                { Percentile = 2, MinSigmaValue = 1.3, MaxSigmaValue = 3 };
            MzLibSpectralAveragingOptions options = new MzLibSpectralAveragingOptions(specOptions);
            MzLibAveragingOptionsViewModel optionsVM = new(options);
            optionsVM.SpectraFileProcessingType = SpectraFileProcessingType.AverageEverynScansWithOverlap;
            optionsVM.ScanOverlap = 3;

            optionsVM.SpectraFileProcessingType = SpectraFileProcessingType.AverageEverynScans;
            Assert.That(optionsVM.ScanOverlap == 0);

            optionsVM.SpectraFileProcessingType = SpectraFileProcessingType.AverageDDAScansWithOverlap;
            Assert.That(optionsVM.ScanOverlap == 3);

            optionsVM.SavedPath = Path.Combine(TestFolder, "testingtesting.toml");
            Assert.That(optionsVM.SavedPath == Path.Combine(TestFolder, "testingtesting.toml"));
            Assert.That(optionsVM.Name == "testingtesting");
        }
    }
}
