## Base image is the Alpine Linux distro with .NET Core runtime
FROM mcr.microsoft.com/dotnet/runtime:5.0-nanoserver-1809

## Copies contents of the installer folder into the Docker image
ADD /InstalledFiles/ /metamorpheus/

## Set the entrypoint of the Docker image to CMD.exe
ENTRYPOINT ["/metamorpheus/CMD.exe"]