using MassSpectrometry;
using MzLibUtil;
using Proteomics;
using Omics.Fragmentation;
using Proteomics.ProteolyticDigestion;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Omics.Modifications;
using System.Collections.Concurrent;
using EngineLayer.Util;
using Omics;
using Readers.SpectralLibrary;

namespace EngineLayer.ClassicSearch
{
    public class ClassicSearchEngine : MetaMorpheusEngine
    {
        private readonly SpectralLibrary SpectralLibrary;
        private readonly MassDiffAcceptor SearchMode;
        private readonly List<IBioPolymer> Proteins;
        private readonly List<Modification> FixedModifications;
        private readonly List<Modification> VariableModifications;
        private readonly List<SilacLabel> SilacLabels;
        private readonly (SilacLabel StartLabel, SilacLabel EndLabel)? TurnoverLabels;
        private readonly SpectralMatch[] SpectralMatches;
        private readonly Ms2ScanWithSpecificMass[] ArrayOfSortedMS2Scans;
        private readonly double[] MyScanPrecursorMasses;
        private readonly bool WriteSpectralLibrary;
        private readonly bool WriteDigestionCounts;
        private readonly object[] Locks;
        public readonly ConcurrentDictionary<(string Accession, string BaseSequence), int> DigestionCountDictionary; // Used to track the amount of digestion products from each protein when the option is enabled.

        public ClassicSearchEngine(SpectralMatch[] globalPsms, Ms2ScanWithSpecificMass[] arrayOfSortedMS2Scans,
            List<Modification> variableModifications, List<Modification> fixedModifications, List<SilacLabel> silacLabels, SilacLabel startLabel, SilacLabel endLabel,
            List<IBioPolymer> proteinList, MassDiffAcceptor searchMode, CommonParameters commonParameters, List<(string FileName, CommonParameters Parameters)> fileSpecificParameters,
            SpectralLibrary spectralLibrary, List<string> nestedIds, bool writeSpectralLibrary, bool writeDigestionCounts = false)
            : base(commonParameters, fileSpecificParameters, nestedIds)
        {
            SpectralMatches = globalPsms;
            ArrayOfSortedMS2Scans = arrayOfSortedMS2Scans;
            MyScanPrecursorMasses = arrayOfSortedMS2Scans.Select(b => b.PrecursorMass).ToArray();
            VariableModifications = variableModifications;
            FixedModifications = fixedModifications;
            SilacLabels = silacLabels;
            if (startLabel != null || endLabel != null) //else it's null
            {
                TurnoverLabels = (startLabel, endLabel);
            }

            SearchMode = searchMode;
            SpectralLibrary = spectralLibrary;
            WriteSpectralLibrary = writeSpectralLibrary;
            WriteDigestionCounts = writeDigestionCounts;
            DigestionCountDictionary = new();

            // Create one lock for each PSM to ensure thread safety
            Locks = new object[SpectralMatches.Length];
            for (int i = 0; i < Locks.Length; i++)
            {
                Locks[i] = new object();
            }

            // if we're doing a spectral library search, we can skip the reverse protein decoys generated by metamorpheus.
            // we will generate reverse peptide decoys w/ in the code just below this (and calculate spectral angles for them later).
            // we have to generate the reverse peptides instead of the usual reverse proteins because we generate decoy spectral
            // library spectra from their corresponding paired target peptides
            Proteins = spectralLibrary == null ? proteinList : proteinList.Where(p => !p.IsDecoy).ToList();
        }

        // Override for constructing from Protein
        public ClassicSearchEngine(SpectralMatch[] globalPsms, Ms2ScanWithSpecificMass[] arrayOfSortedMS2Scans,
            List<Modification> variableModifications, List<Modification> fixedModifications, List<SilacLabel> silacLabels, SilacLabel startLabel, SilacLabel endLabel,
            List<Protein> proteinList, MassDiffAcceptor searchMode, CommonParameters commonParameters, List<(string FileName, CommonParameters Parameters)> fileSpecificParameters,
            SpectralLibrary spectralLibrary, List<string> nestedIds, bool writeSpectralLibrary)
            : this(globalPsms, arrayOfSortedMS2Scans, variableModifications, fixedModifications, silacLabels, startLabel, endLabel,
                proteinList.Cast<IBioPolymer>().ToList(), searchMode, commonParameters, fileSpecificParameters, spectralLibrary, nestedIds, writeSpectralLibrary)
        {
        }

        protected override MetaMorpheusEngineResults RunSpecific()
        {
           Status("Getting ms2 scans...");

            double proteinsSearched = 0;
            int oldPercentProgress = 0;
            
            Status("Performing classic search...");

            if (Proteins.Any())
            {
                int maxThreadsPerFile = CommonParameters.MaxThreadsToUsePerFile;
                var proteinPartioner = Partitioner.Create(0, Proteins.Count);
                
                Parallel.ForEach(
                    proteinPartioner,
                    new ParallelOptions { MaxDegreeOfParallelism = maxThreadsPerFile },
                    (range, loopState) =>
                {
                    var targetFragmentsForEachDissociationType = new Dictionary<DissociationType, List<Product>>();
                    var decoyFragmentsForEachDissociationType = new Dictionary<DissociationType, List<Product>>();

                    // check if we're supposed to autodetect dissociation type from the scan header or not
                    if (CommonParameters.DissociationType == DissociationType.Autodetect)
                    {
                        foreach (var item in GlobalVariables.AllSupportedDissociationTypes.Where(p => p.Value != DissociationType.Autodetect))
                        {
                            targetFragmentsForEachDissociationType.Add(item.Value, new List<Product>());
                            decoyFragmentsForEachDissociationType.Add(item.Value, new List<Product>());
                        }
                    }
                    else
                    {
                        targetFragmentsForEachDissociationType.Add(CommonParameters.DissociationType, new List<Product>());
                        decoyFragmentsForEachDissociationType.Add(CommonParameters.DissociationType, new List<Product>());
                    }

                    for (int i = range.Item1; i < range.Item2; i++)
                    {
                        // Stop loop if canceled
                        if (GlobalVariables.StopLoops) { return; }

                        // digest each protein into peptides and search for each peptide in all spectra within precursor mass tolerance
                        foreach (var specificBioPolymer in Proteins[i].Digest(CommonParameters.DigestionParams, FixedModifications, VariableModifications, SilacLabels, TurnoverLabels))
                        {
                            if (WriteDigestionCounts)
                                DigestionCountDictionary.Increment((specificBioPolymer.Parent.Accession, specificBioPolymer.BaseSequence));
                                
                            IBioPolymerWithSetMods reversedOnTheFlyDecoy = null;

                            if (SpectralLibrary != null && specificBioPolymer is PeptideWithSetModifications pep)
                            {
                                int[] newAAlocations = new int[specificBioPolymer.BaseSequence.Length];
                                reversedOnTheFlyDecoy = pep.GetReverseDecoyFromTarget(newAAlocations);
                            }

                            // clear fragments from the last peptide
                            foreach (var fragmentSet in targetFragmentsForEachDissociationType)
                            {
                                fragmentSet.Value.Clear();
                                decoyFragmentsForEachDissociationType[fragmentSet.Key].Clear();
                            }

                            // score each scan that has an acceptable precursor mass
                            foreach (ScanWithIndexAndNotchInfo scan in GetAcceptableScans(specificBioPolymer.MonoisotopicMass, SearchMode))
                            {
                                Ms2ScanWithSpecificMass theScan = ArrayOfSortedMS2Scans[scan.ScanIndex];
                                var dissociationType = CommonParameters.DissociationType == DissociationType.Autodetect ?
                                    theScan.TheScan.DissociationType.Value : CommonParameters.DissociationType;

                                if (!targetFragmentsForEachDissociationType.TryGetValue(dissociationType, out var peptideTheorProducts))
                                {
                                    //TODO: print some kind of warning here. the scan header dissociation type was unknown
                                    continue;
                                }

                                // check if we've already generated theoretical fragments for this peptide+dissociation type
                                if (peptideTheorProducts.Count == 0)
                                {
                                    specificBioPolymer.Fragment(dissociationType, CommonParameters.DigestionParams.FragmentationTerminus, peptideTheorProducts);
                                }

                                // match theoretical target ions to spectrum
                                List<MatchedFragmentIon> matchedIons = MatchFragmentIons(theScan, peptideTheorProducts, CommonParameters,
                                        matchAllCharges: WriteSpectralLibrary);

                                // calculate the peptide's score
                                double thisScore = CalculatePeptideScore(theScan.TheScan, matchedIons, fragmentsCanHaveDifferentCharges: WriteSpectralLibrary);

                                AddPeptideCandidateToPsm(scan, thisScore, specificBioPolymer, matchedIons);

                                if (SpectralLibrary != null)
                                {
                                    DecoyScoreForSpectralLibrarySearch(scan, reversedOnTheFlyDecoy, decoyFragmentsForEachDissociationType, dissociationType);
                                }
                            }
                        }

                        // report search progress (proteins searched so far out of total proteins in database)
                        proteinsSearched++;
                        var percentProgress = (int)((proteinsSearched / Proteins.Count) * 100);

                        if (percentProgress > oldPercentProgress)
                        {
                            oldPercentProgress = percentProgress;
                            ReportProgress(new ProgressEventArgs(percentProgress, "Performing classic search... ", NestedIds));
                        }
                    }
                });
            }

            foreach (SpectralMatch psm in SpectralMatches.Where(p => p != null))
            {
                psm.ResolveAllAmbiguities();
            }

            return new MetaMorpheusEngineResults(this);
        }

        private void DecoyScoreForSpectralLibrarySearch(ScanWithIndexAndNotchInfo scan, IBioPolymerWithSetMods reversedOnTheFlyDecoy, Dictionary<DissociationType, List<Product>> decoyFragmentsForEachDissociationType, DissociationType dissociationType)
        {
            // match decoy ions for decoy-on-the-fly
            var decoyTheoreticalFragments = decoyFragmentsForEachDissociationType[dissociationType];

            if (decoyTheoreticalFragments.Count == 0)
            {
                reversedOnTheFlyDecoy.Fragment(dissociationType, CommonParameters.DigestionParams.FragmentationTerminus, decoyTheoreticalFragments);
            }
            Ms2ScanWithSpecificMass theScan = ArrayOfSortedMS2Scans[scan.ScanIndex];
            var decoyMatchedIons = MatchFragmentIons(theScan, decoyTheoreticalFragments, CommonParameters,
                matchAllCharges: WriteSpectralLibrary);

            // calculate decoy's score
            var decoyScore = CalculatePeptideScore(theScan.TheScan, decoyMatchedIons, fragmentsCanHaveDifferentCharges: WriteSpectralLibrary);

            AddPeptideCandidateToPsm(scan, decoyScore, reversedOnTheFlyDecoy, decoyMatchedIons);
        }

        private void AddPeptideCandidateToPsm(ScanWithIndexAndNotchInfo scan, double thisScore, IBioPolymerWithSetMods peptide, List<MatchedFragmentIon> matchedIons)
        {
            bool meetsScoreCutoff = thisScore >= CommonParameters.ScoreCutoff;

            // this is thread-safe because even if the score improves from another thread writing to this PSM,
            // the lock combined with AddOrReplace method will ensure thread safety
            if (meetsScoreCutoff)
            {
                // valid hit (met the cutoff score); lock the scan to prevent other threads from accessing it
                lock (Locks[scan.ScanIndex])
                {
                    bool scoreImprovement = SpectralMatches[scan.ScanIndex] == null || (thisScore - SpectralMatches[scan.ScanIndex].RunnerUpScore) > -SpectralMatch.ToleranceForScoreDifferentiation;

                    if (!scoreImprovement) 
                        return;

                    // if the PSM is null, create a new one; otherwise, add or replace the peptide
                    if (SpectralMatches[scan.ScanIndex] == null)
                        if (GlobalVariables.AnalyteType == AnalyteType.Oligo)
                            SpectralMatches[scan.ScanIndex] = new OligoSpectralMatch(peptide, scan.Notch, thisScore, scan.ScanIndex, ArrayOfSortedMS2Scans[scan.ScanIndex], CommonParameters, matchedIons);
                        else
                            SpectralMatches[scan.ScanIndex] = new PeptideSpectralMatch(peptide, scan.Notch, thisScore, scan.ScanIndex, ArrayOfSortedMS2Scans[scan.ScanIndex], CommonParameters, matchedIons);
                    else
                        SpectralMatches[scan.ScanIndex].AddOrReplace(peptide, thisScore, scan.Notch, CommonParameters.ReportAllAmbiguity, matchedIons);
                }
            }
        }

        private IEnumerable<ScanWithIndexAndNotchInfo> GetAcceptableScans(double peptideMonoisotopicMass, MassDiffAcceptor searchMode)
        {
            foreach (AllowedIntervalWithNotch allowedIntervalWithNotch in searchMode.GetAllowedPrecursorMassIntervalsFromTheoreticalMass(peptideMonoisotopicMass))
            {
                int scanIndex = GetFirstScanWithMassOverOrEqual(allowedIntervalWithNotch.Minimum);
                if (scanIndex < ArrayOfSortedMS2Scans.Length)
                {
                    var scanMass = MyScanPrecursorMasses[scanIndex];
                    while (scanMass <= allowedIntervalWithNotch.Maximum)
                    {
                        yield return new ScanWithIndexAndNotchInfo(allowedIntervalWithNotch.Notch, scanIndex);
                        scanIndex++;
                        if (scanIndex == ArrayOfSortedMS2Scans.Length)
                        {
                            break;
                        }

                        scanMass = MyScanPrecursorMasses[scanIndex];
                    }
                }
            }
        }

        private int GetFirstScanWithMassOverOrEqual(double minimum)
        {
            int index = Array.BinarySearch(MyScanPrecursorMasses, minimum);
            if (index < 0)
            {
                index = ~index;
            }

            // index of the first element that is larger than value
            return index;
        }
    }
}