using System;
using EngineLayer;
using MzLibUtil;
using Omics.Modifications;
using System.Collections.Generic;

namespace TaskLayer
{
    /// <summary>
    /// Parameters governing the circular peptide search task.
    ///
    /// Kept intentionally minimal — the search honours the same
    /// <see cref="CommonParameters"/> (protease, missed cleavages, tolerances,
    /// dissociation type, fixed/variable mods) as the classic search.
    /// Circular-specific knobs live here.
    /// </summary>
    public class CircularSearchParameters
    {
        public CircularSearchParameters()
        {
            // ── Precursor / mass-diff ─────────────────────────────────────────
            MassDiffAcceptorType = MassDiffAcceptorType.OneMM;
            CustomMdac = string.Empty;

            // ── Tolerances ────────────────────────────────────────────────────
            ProductMassTolerance = new PpmTolerance(20);

            // ── Fragment filtering ────────────────────────────────────────────
            // Minimum length (in residues) of internal fragment ions used to
            // score circular peptides.  Must be ≥ 2 (single-residue internal
            // ions are not physically meaningful).
            MinInternalFragmentLength = 3;

            // ── Scoring ───────────────────────────────────────────────────────
            MinScore = 1;

            // ── Decoy ─────────────────────────────────────────────────────────
            // Circular decoys are ALWAYS generated by randomly shuffling the
            // canonical ring sequence. Reverse is invalid for circular sequences
            // because the reverse of a rotation may itself be a valid rotation of
            // the same ring. Decoy generation is handled internally by
            // CircularSearchTask and never delegated to DecoyProteinGenerator.
            SearchTarget = true;
            GenerateDecoys = true;

            // ── Output ────────────────────────────────────────────────────────
            WriteMzId = true;
            WriteHighQValuePsms = true;
            WriteDecoys = true;
            WriteContaminants = true;

            // ── Parsimony / protein grouping ──────────────────────────────────
            DoParsimony = true;
            NoOneHitWonders = false;

            // ── Modification output selection ─────────────────────────────────
            ModsToWriteSelection = new Dictionary<string, int>
            {
                { "Common Biological", 3 },
                { "Less Common",       3 },
                { "Metal",             3 },
                { "UniProt",           2 },
            };

            MaxFragmentSize = 30000.0;
            DisposeOfFileWhenDone = true;
        }

        // ── Properties ────────────────────────────────────────────────────────

        public bool DisposeOfFileWhenDone { get; set; }
        public MassDiffAcceptorType MassDiffAcceptorType { get; set; }
        public string CustomMdac { get; set; }

        /// <summary>
        /// Product (fragment) mass tolerance used when matching internal ions
        /// against experimental fragments. Default: 20 ppm.
        /// </summary>
        public Tolerance ProductMassTolerance { get; set; }

        private int _minInternalFragmentLength;

        /// <summary>
        /// Minimum residue length of internal fragment ions used when scoring
        /// <see cref="CircularPeptideWithSetModifications"/> precursors.
        /// Values below 2 are silently raised to 2 at assignment time.
        /// </summary>
        public int MinInternalFragmentLength
        {
            get => _minInternalFragmentLength;
            set => _minInternalFragmentLength = Math.Max(2, value);
        }

        /// <summary>
        /// Minimum PSM score required to retain a match. Default: 1.
        /// </summary>
        public double MinScore { get; set; }

        public bool SearchTarget { get; set; }

        /// <summary>
        /// When true, one randomly shuffled decoy <see cref="CircularProtein"/> is
        /// generated per target protein. Decoys are generated internally and never
        /// produced by <see cref="UsefulProteomicsDatabases.DecoyProteinGenerator"/>,
        /// which does not support circular sequences.
        /// </summary>
        public bool GenerateDecoys { get; set; }

        public bool WriteMzId { get; set; }
        public bool WriteHighQValuePsms { get; set; }
        public bool WriteDecoys { get; set; }
        public bool WriteContaminants { get; set; }
        public bool DoParsimony { get; set; }
        public bool NoOneHitWonders { get; set; }

        public double MaxFragmentSize { get; set; }
        public Dictionary<string, int> ModsToWriteSelection { get; set; }
    }
}