using EngineLayer;
using EngineLayer.CircularSearch;
using EngineLayer.DatabaseLoading;
using EngineLayer.FdrAnalysis;
using MassSpectrometry;
using MzLibUtil;
using Omics;
using Omics.Modifications;
using Proteomics;
using Proteomics.ProteolyticDigestion;
using System;
using System.Collections.Generic;
using System.Text;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using UsefulProteomicsDatabases;

namespace TaskLayer
{
    /// <summary>
    /// A MetaMorpheus task that searches MS/MS spectra against a database of
    /// head-to-tail cyclic proteins represented as <see cref="CircularProtein"/>
    /// entries.
    ///
    /// WORKFLOW
    /// --------
    /// 1. Load spectra files.
    /// 2. Load protein databases — any <see cref="Protein"/> entry is wrapped in
    ///    a <see cref="CircularProtein"/> so that its sequence is canonicalized
    ///    and the circular digestion logic is applied.
    /// 3. For each spectra file, run <see cref="CircularSearchEngine"/> which
    ///    digests each <see cref="CircularProtein"/>, scores precursor candidates,
    ///    and populates a PSM array.
    /// 4. Perform FDR calculation and write output files.
    ///
    /// OUTPUT FILES
    /// ------------
    /// • CircularPeptideSpectralMatches.psmtsv  – all PSMs passing filters
    /// • CircularPeptides.psmtsv  – unique peptide-level results (best PSM per full sequence)
    /// </summary>
    public class CircularSearchTask : MetaMorpheusTask
    {
        public CircularSearchTask() : base(MyTask.CircularSearch)
        {
            CommonParameters = new CommonParameters();
            CircularSearchParameters = new CircularSearchParameters();
        }

        public CircularSearchParameters CircularSearchParameters { get; set; }

        // ── RunSpecific ───────────────────────────────────────────────────────

        protected override MyTaskResults RunSpecific(
            string outputFolder,
            List<DbForTask> dbFilenameList,
            List<string> currentRawFileList,
            string taskId,
            FileSpecificParameters[] fileSettingsList)
        {
            MyTaskResults = new MyTaskResults(this);

            if (fileSettingsList.Length < currentRawFileList.Count)
            {
                throw new MetaMorpheusException(
                    $"Mismatch between spectra files ({currentRawFileList.Count}) " +
                    $"and file-specific settings ({fileSettingsList.Length}). " +
                    "Each spectra file must have a corresponding entry in the file settings list.");
            }

            // ── Load modifications ────────────────────────────────────────────
            LoadModifications(taskId,
                out var variableModifications,
                out var fixedModifications,
                out var localizeableModificationTypes);

            // ── Load proteins as CircularProteins ─────────────────────────────
            Status("Loading circular protein database...", taskId);

            // Always pass DecoyType.None to DatabaseLoadingEngine.
            // Circular decoys cannot be generated by DecoyProteinGenerator:
            //   - Reverse: may produce a valid rotation of the same ring (invalid decoy).
            //   - Random/Shuffle: not implemented in DecoyProteinGenerator.
            // Decoys are generated below by randomly shuffling each target's
            // canonical ring sequence.
            var dbLoader = new DatabaseLoadingEngine(
                CommonParameters,
                FileSpecificParameters,
                [taskId],
                dbFilenameList,
                taskId,
                DecoyType.None,
                CircularSearchParameters.SearchTarget,
                localizeableModificationTypes,
                TargetContaminantAmbiguity.RemoveContaminant);

            var dbResults = (DatabaseLoadingEngineResults)dbLoader.Run();
            var bioPolymers = dbResults.BioPolymers;

            // Wrap every loaded protein as a CircularProtein.
            // Sequences are canonicalized by the CircularProtein constructor.
            var targetProteins = bioPolymers
                .OfType<Protein>()
                .Select(p => CircularProtein.FromProtein(p))
                .ToList();

            if (!targetProteins.Any())
            {
                Warn("No proteins found in the database — circular search will produce no results.");
                return MyTaskResults;
            }

            // Generate random-shuffle decoys for circular proteins.
            // One decoy per target: the canonical ring sequence is randomly shuffled,
            // then canonicalized. If the shuffle accidentally produces the same
            // canonical sequence as the target (extremely rare for N > 4), the shuffle
            // is retried up to 10 times before the decoy is skipped.
            var circularProteins = new List<CircularProtein>(targetProteins);
            if (CircularSearchParameters.GenerateDecoys)
            {
                var rng = new Random(42); // fixed seed for reproducibility
                foreach (var target in targetProteins)
                {
                    string decoySeq = null;

                    for (int attempt = 0; attempt < 10; attempt++)
                    {
                        char[] arr = target.BaseSequence.ToCharArray();
                        // Fisher-Yates shuffle
                        for (int i = arr.Length - 1; i > 0; i--)
                        {
                            int j = rng.Next(i + 1);
                            (arr[i], arr[j]) = (arr[j], arr[i]);
                        }
                        string candidate = new string(arr);
                        // Reject if canonicalized shuffle equals the target (invalid decoy)
                        if (CircularProtein.GetCanonicalRotation(candidate) != target.BaseSequence)
                        {
                            decoySeq = candidate;
                            break;
                        }
                    }

                    if (decoySeq == null)
                    {
                        Warn($"Could not generate a valid random decoy for {target.Accession} after 10 attempts — skipping.");
                        continue;
                    }

                    var decoy = new CircularProtein(
                        sequence: decoySeq,
                        accession: "DECOY_" + target.Accession,
                        organism: target.Organism,
                        geneNames: target.GeneNames?.ToList(),
                        name: target.Name,
                        fullName: target.FullName,
                        isDecoy: true,
                        isContaminant: target.IsContaminant,
                        databaseFilePath: target.DatabaseFilePath);

                    circularProteins.Add(decoy);
                }
            }

            // ── Mass-difference acceptor ──────────────────────────────────────
            var massDiffAcceptor = GetMassDiffAcceptor(
                CommonParameters.PrecursorMassTolerance,
                CircularSearchParameters.MassDiffAcceptorType,
                CircularSearchParameters.CustomMdac);

            // ── Validate spectra file list ────────────────────────────────────
            if (currentRawFileList == null || currentRawFileList.Count == 0)
            {
                Warn("No spectra files were provided — circular search cannot proceed.");
                return MyTaskResults;
            }

            // ── Search each spectra file ──────────────────────────────────────
            var myFileManager = new MyFileManager(
                CircularSearchParameters.DisposeOfFileWhenDone);

            var allPsms = new List<SpectralMatch>();
            int completedFiles = 0;

            // Pre-compute file-specific params for every spectra file (once each)
            var allFileParams = new CommonParameters[currentRawFileList.Count];
            for (int i = 0; i < currentRawFileList.Count; i++)
            {
                allFileParams[i] = SetAllFileSpecificCommonParams(
                    CommonParameters, fileSettingsList[i]);
            }

            // Pre-load first file
            string firstFile = currentRawFileList[0];
            var nextFileTask = new Task<MsDataFile>(
                () => myFileManager.LoadFile(firstFile, allFileParams[0]));
            nextFileTask.Start();

            for (int spectraFileIndex = 0;
                 spectraFileIndex < currentRawFileList.Count;
                 spectraFileIndex++)
            {
                if (GlobalVariables.StopLoops) break;

                string origDataFile = currentRawFileList[spectraFileIndex];
                StartingDataFile(origDataFile,
                    [taskId, "Individual Spectra Files", origDataFile]);

                var combinedParams = allFileParams[spectraFileIndex];

                var thisId = new List<string> { taskId, "Individual Spectra Files", origDataFile };
                NewCollection(Path.GetFileName(origDataFile), thisId);
                Status("Loading spectra file...", thisId);

                nextFileTask.Wait();
                var myMsDataFile = nextFileTask.Result;

                // Begin loading the next file asynchronously
                if (spectraFileIndex < currentRawFileList.Count - 1)
                {
                    int next = spectraFileIndex + 1;
                    nextFileTask = new Task<MsDataFile>(
                        () => myFileManager.LoadFile(
                            currentRawFileList[next], allFileParams[next]));
                    nextFileTask.Start();
                }

                Status("Getting MS2 scans...", thisId);
                var ms2Scans = GetMs2Scans(myMsDataFile, origDataFile, combinedParams)
                    .OrderBy(b => b.PrecursorMass)
                    .ToArray();

                myFileManager.DoneWithFile(origDataFile);

                var fileSpecificPsms = new SpectralMatch[ms2Scans.Length];

                Status("Searching...", thisId);

                var engine = new CircularSearchEngine(
                    fileSpecificPsms,
                    ms2Scans,
                    variableModifications,
                    fixedModifications,
                    circularProteins,
                    massDiffAcceptor,
                    combinedParams,
                    FileSpecificParameters,
                    thisId,
                    CircularSearchParameters.MinInternalFragmentLength);

                engine.Run();

                ReportProgress(new ProgressEventArgs(100, "Done with search!", thisId));

                allPsms.AddRange(fileSpecificPsms.Where(p => p != null));

                completedFiles++;
                FinishedDataFile(origDataFile,
                    [taskId, "Individual Spectra Files", origDataFile]);
                ReportProgress(new ProgressEventArgs(
                    (int)(completedFiles * 100.0 / currentRawFileList.Count),
                    "Searching...",
                    [taskId, "Individual Spectra Files"]));
            }

            // ── FDR ──────────────────────────────────────────────────────────
            Status("Calculating FDR...", taskId);

            new FdrAnalysisEngine(
                allPsms, massDiffAcceptor.NumNotches,
                CommonParameters, FileSpecificParameters,
                [taskId]).Run();

            // ── Write results ─────────────────────────────────────────────────
            Status("Writing results...", taskId);

            IEnumerable<SpectralMatch> writablePsms = CircularSearchParameters.WriteHighQValuePsms
                ? allPsms
                : allPsms.Where(p => p.FdrInfo?.QValue <= 0.01);

            if (!CircularSearchParameters.WriteDecoys)
                writablePsms = writablePsms.Where(p => !p.IsDecoy);

            if (!CircularSearchParameters.WriteContaminants)
                writablePsms = writablePsms.Where(p => !p.IsContaminant);

            // PSM-level TSV — inherited protected static from MetaMorpheusTask
            string psmPath = Path.Combine(outputFolder, "CircularPeptideSpectralMatches.psmtsv");
            var writablePsmsList = writablePsms.ToList();
            WritePsmsToTsv(
                writablePsmsList,
                psmPath,
                new Dictionary<string, int>());
            FinishedWritingFile(psmPath, [taskId]);

            // Unique peptide-level TSV — best-scoring PSM per full sequence
            string peptidePath = Path.Combine(outputFolder, "CircularPeptides.psmtsv");
            var uniquePeptides = writablePsmsList
                .GroupBy(p => p.FullSequence)
                .Select(g => g.OrderByDescending(p => p.Score).First())
                .OrderByDescending(p => p.Score)
                .ToList();
            WritePsmsToTsv(
                uniquePeptides,
                peptidePath,
                new Dictionary<string, int>());
            FinishedWritingFile(peptidePath, [taskId]);

            MyTaskResults.AddResultText(
                $"Circular search complete. {writablePsmsList.Count} PSMs found " +
                $"({allPsms.Count(p => p.FdrInfo?.QValue <= 0.01)} at q≤0.01), " +
                $"{uniquePeptides.Count} unique peptides.");

            return MyTaskResults;
        }

        // ── Mass-diff acceptor factory ────────────────────────────────────────

        public static MassDiffAcceptor GetMassDiffAcceptor(
            Tolerance precursorMassTolerance,
            MassDiffAcceptorType type,
            string customMdac)
        {
            return type switch
            {
                MassDiffAcceptorType.Exact =>
                    precursorMassTolerance is PpmTolerance
                        ? new SinglePpmAroundZeroSearchMode(precursorMassTolerance.Value)
                        : new SingleAbsoluteAroundZeroSearchMode(precursorMassTolerance.Value),

                MassDiffAcceptorType.OneMM =>
                    new DotMassDiffAcceptor("1mm",
                        [0, 1.0029], precursorMassTolerance),

                MassDiffAcceptorType.TwoMM =>
                    new DotMassDiffAcceptor("2mm",
                        [0, 1.0029, 2.0052], precursorMassTolerance),

                MassDiffAcceptorType.ThreeMM =>
                    new DotMassDiffAcceptor("3mm",
                        [0, 1.0029, 2.0052, 3.0077], precursorMassTolerance),

                MassDiffAcceptorType.Open =>
                    new OpenSearchMode(),

                MassDiffAcceptorType.ModOpen =>
                    new IntervalMassDiffAcceptor("-187andUp",
                        [new DoubleRange(-187, double.PositiveInfinity)]),

                MassDiffAcceptorType.Custom =>
                    ParseSearchMode(customMdac),

                _ => throw new MetaMorpheusException(
                    $"Unknown MassDiffAcceptorType: {type}")
            };
        }

        private static MassDiffAcceptor ParseSearchMode(string text)
        {
            try
            {
                var split = text.Split(' ');
                return split[1] switch
                {
                    "dot" => ParseDotMode(split),
                    "interval" => ParseIntervalMode(split),
                    "OpenSearch" => new OpenSearchMode(),
                    "daltonsAroundZero" =>
                        new SingleAbsoluteAroundZeroSearchMode(
                            double.Parse(split[2], CultureInfo.InvariantCulture)),
                    "ppmAroundZero" =>
                        new SinglePpmAroundZeroSearchMode(
                            double.Parse(split[2], CultureInfo.InvariantCulture)),
                    _ => throw new MetaMorpheusException(
                        $"Unrecognized search mode type: {split[1]}")
                };
            }
            catch (Exception e)
            {
                throw new MetaMorpheusException(
                    $"Could not parse search mode string: {e.Message}");
            }
        }

        private static MassDiffAcceptor ParseDotMode(string[] split)
        {
            double[] massShifts = split[4].Split(',')
                .Select(p => double.Parse(p, CultureInfo.InvariantCulture))
                .ToArray();
            double toleranceValue = double.Parse(
                split[2].Replace("±", ""), CultureInfo.InvariantCulture);

            Tolerance tol = split[3].ToUpperInvariant() == "PPM"
                ? new PpmTolerance(toleranceValue)
                : new AbsoluteTolerance(toleranceValue);

            return new DotMassDiffAcceptor(split[0], massShifts, tol);
        }

        private static MassDiffAcceptor ParseIntervalMode(string[] split)
        {
            var ranges = Array.ConvertAll(split[2].Split(';'),
                b => new DoubleRange(
                    double.Parse(b.Trim('[', ']').Split(',')[0],
                        CultureInfo.InvariantCulture),
                    double.Parse(b.Trim('[', ']').Split(',')[1],
                        CultureInfo.InvariantCulture)));
            return new IntervalMassDiffAcceptor(split[0], ranges);
        }
    }
}