using EngineLayer;
using Omics.Modifications;
using System.Collections.Generic;
using UsefulProteomicsDatabases;

namespace TaskLayer
{
    /// <summary>
    /// Parameters governing the circular peptide search task.
    ///
    /// Kept intentionally minimal — the search honours the same
    /// <see cref="CommonParameters"/> (protease, missed cleavages, tolerances,
    /// dissociation type, fixed/variable mods) as the classic search.
    /// Circular-specific knobs live here.
    /// </summary>
    public class CircularSearchParameters
    {
        public CircularSearchParameters()
        {
            // ── Precursor / mass-diff ─────────────────────────────────────────
            MassDiffAcceptorType = MassDiffAcceptorType.OneMM;
            CustomMdac = string.Empty;

            // ── Fragment filtering ────────────────────────────────────────────
            // Minimum length (in residues) of internal fragment ions used to
            // score circular peptides.  Must be ≥ 2 (single-residue internal
            // ions are not physically meaningful).
            MinInternalFragmentLength = 3;

            // ── Decoy ─────────────────────────────────────────────────────────
            // Circular decoys are generated by reversing the canonical sequence
            // (which is already the lexicographically smallest rotation).
            SearchTarget = true;
            DecoyType = DecoyType.Reverse;

            // ── Output ────────────────────────────────────────────────────────
            WriteMzId = true;
            WriteHighQValuePsms = true;
            WriteDecoys = true;
            WriteContaminants = true;

            // ── Parsimony / protein grouping ──────────────────────────────────
            DoParsimony = true;
            NoOneHitWonders = false;

            // ── Modification output selection ─────────────────────────────────
            ModsToWriteSelection = new Dictionary<string, int>
            {
                { "Common Biological", 3 },
                { "Less Common",       3 },
                { "Metal",             3 },
                { "UniProt",           2 },
            };

            MaxFragmentSize = 30000.0;
            DisposeOfFileWhenDone = true;
        }

        // ── Properties ────────────────────────────────────────────────────────

        public bool DisposeOfFileWhenDone { get; set; }
        public MassDiffAcceptorType MassDiffAcceptorType { get; set; }
        public string CustomMdac { get; set; }

        /// <summary>
        /// Minimum residue length of internal fragment ions used when scoring
        /// <see cref="CircularPeptideWithSetModifications"/> precursors.
        /// Values below 2 are silently raised to 2.
        /// </summary>
        public int MinInternalFragmentLength { get; set; }

        public bool SearchTarget { get; set; }
        public DecoyType DecoyType { get; set; }

        public bool WriteMzId { get; set; }
        public bool WriteHighQValuePsms { get; set; }
        public bool WriteDecoys { get; set; }
        public bool WriteContaminants { get; set; }
        public bool DoParsimony { get; set; }
        public bool NoOneHitWonders { get; set; }

        public double MaxFragmentSize { get; set; }
        public Dictionary<string, int> ModsToWriteSelection { get; set; }
    }
}