## Base image is the Alpine Linux distro with .NET Core runtime
FROM mcr.microsoft.com/dotnet/runtime:6.0-nanoserver-1809

## Copies contents of the installer folder into the Docker image
ADD CMD/bin/x64/Release/net6.0/ /metamorpheus/

## Set the entrypoint of the Docker image to CMD.exe
ENTRYPOINT ["/metamorpheus/CMD.exe"]

