ListOfModListsFixed = ["Mods\\f.txt"]
ListOfModListsVariable = ["Mods\\v.txt"]
ListOfModListsLocalize = ["Mods\\ptmlist.txt"]
ProductMassTolerance = "±0.0100 Absolute"
ClassicSearch = true
DoParsimony = false
NoOneHitWonders = false
Quantify = false
QuantifyRtTol = 3.0
QuantifyPpmTol = 5.0
DoHistogramAnalysis = false
SearchDecoy = true
SearchModes = ["10ppmAroundZero ppmAroundZero 10", "5ppmAroundZero ppmAroundZero 5"]
ConserveMemory = false
TaskType = "Search"
InitiatorMethionineBehavior = "Variable"
MaxMissedCleavages = 2
MaxModificationIsoforms = 4096
Protease = "trypsin"
BIons = true
YIons = true
ZdotIons = false
CIons = false
