using EngineLayer.ClassicSearch;
using EngineLayer;
using NUnit.Framework;
using Omics.Modifications;
using Omics;
using Readers;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using EngineLayer.DatabaseLoading;
using TaskLayer;
using Transcriptomics;
using MassSpectrometry;
using MzLibUtil;
using Transcriptomics.Digestion;
using UsefulProteomicsDatabases;

namespace Test.Transcriptomics;

[TestFixture]
public class SearchTaskWithRna
{
    public static RnaSearchParameters SearchParameters;
    public static CommonParameters CommonParameters;
    public static string SixmerSpectraFilePath = Path.Combine(TestContext.CurrentContext.TestDirectory, "Transcriptomics", "TestData", "GUACUG_NegativeMode_Sliced.mzML");
    public static string SixmerDatabaseFilePath = Path.Combine(TestContext.CurrentContext.TestDirectory, "Transcriptomics", "TestData", "6mer.fasta");

    [OneTimeSetUp]
    public static void Setup()
    {
        SearchParameters = new RnaSearchParameters
        {
            DecoyType = DecoyType.Reverse,
            MassDiffAcceptorType = MassDiffAcceptorType.Custom,
            CustomMdac = "Custom interval [-5,5]",
            DisposeOfFileWhenDone = true
        };
        CommonParameters = new CommonParameters
        (
            dissociationType: DissociationType.CID,
            deconvolutionMaxAssumedChargeState: -20,
            deconvolutionIntensityRatio: 3,
            deconvolutionMassTolerance: new PpmTolerance(20),
            precursorMassTolerance: new PpmTolerance(10),
            productMassTolerance: new PpmTolerance(5),
            scoreCutoff: 5,
            totalPartitions: 1,
            maxThreadsToUsePerFile: 1,
            doPrecursorDeconvolution: true,
            useProvidedPrecursorInfo: false,
            digestionParams: new RnaDigestionParams()
        );
    }

    [Test]
    public static void FindsSimpleSixmer()
    {
        List<DbForTask> dbForTask = [new(SixmerDatabaseFilePath, false)];
        List<string> rawFileList = [SixmerSpectraFilePath];
        string taskId = "RnaTestSearch";
        string outputDir = Path.Combine(TestContext.CurrentContext.TestDirectory, "Transcriptomics", "TestOutput");
        if (Directory.Exists(outputDir))
            Directory.Delete(outputDir, true);
        Directory.CreateDirectory(outputDir);


        var searchTask = new SearchTask
        {
            CommonParameters = CommonParameters,
            SearchParameters = SearchParameters
        };

        var results = searchTask.RunTask(outputDir, dbForTask, rawFileList, taskId);

        var files = Directory.GetFiles(outputDir);

        List<string> expectedOutputFiles =
        [
            Path.Combine(outputDir, "AllOligos.osmtsv"),
            Path.Combine(outputDir, "AllOSMs.osmtsv"),
            Path.Combine(outputDir, "AllOSMs_FormattedForPercolator.tab"),
            Path.Combine(outputDir, "results.txt"),
            Path.Combine(outputDir, "AutoGeneratedManuscriptProse.txt"),
            Path.Combine(outputDir, "AllTranscriptGroups.tsv"),
        ];

        foreach (var expectedFile in expectedOutputFiles)
        {
            Assert.That(files, Does.Contain(expectedFile), $"Expected output file {expectedFile} not found.");
        }

        // The OSM writer emits the 5'- and 3'-terminus columns immediately after Essential Sequence.
        var osmHeader = File.ReadLines(Path.Combine(outputDir, "AllOSMs.osmtsv")).First().Split('\t');
        Assert.That(osmHeader.IndexOf(SpectrumMatchFromTsvHeader.EssentialSequence), Is.GreaterThanOrEqualTo(0));
        Assert.That(osmHeader, Does.Contain(SpectrumMatchFromTsvHeader.FivePrimeTerminus));
        Assert.That(osmHeader, Does.Contain(SpectrumMatchFromTsvHeader.ThreePrimeTerminus));
        // Directory.Delete(outputDir, true);
    }

    [Test]
    public static void LabelFreeQuantificationCanRunForRnaSearch()
    {
        List<DbForTask> dbForTask = [new(SixmerDatabaseFilePath, false)];
        List<string> rawFileList = [SixmerSpectraFilePath];
        string taskId = "RnaQuantificationTest";
        string outputDir = Path.Combine(TestContext.CurrentContext.TestDirectory, "Transcriptomics", "QuantificationTestOutput");
        if (Directory.Exists(outputDir))
            Directory.Delete(outputDir, true);
        Directory.CreateDirectory(outputDir);

        var searchParameters = new RnaSearchParameters
        {
            DecoyType = DecoyType.Reverse,
            MassDiffAcceptorType = MassDiffAcceptorType.Custom,
            CustomMdac = "Custom interval [-5,5]",
            DisposeOfFileWhenDone = true,
            DoLabelFreeQuantification = true,
            Normalize = false,
            MatchBetweenRuns = false
        };

        var searchTask = new SearchTask
        {
            CommonParameters = CommonParameters,
            SearchParameters = searchParameters
        };

        try
        {
            searchTask.RunTask(outputDir, dbForTask, rawFileList, taskId);

            Assert.Multiple(() =>
            {
                Assert.That(File.Exists(Path.Combine(outputDir, "AllQuantifiedPeaks.tsv")), Is.True);
                Assert.That(File.Exists(Path.Combine(outputDir, "AllQuantifiedOligos.tsv")), Is.True);
                Assert.That(File.Exists(Path.Combine(outputDir, "AllQuantifiedTranscriptGroups.tsv")), Is.True);
            });

            Assert.That(File.ReadLines(Path.Combine(outputDir, "AllQuantifiedOligos.tsv")).Skip(1), Is.Not.Empty);
            Assert.That(File.ReadLines(Path.Combine(outputDir, "AllQuantifiedPeaks.tsv")).Skip(1), Is.Not.Empty);
        }
        finally
        {
            if (Directory.Exists(outputDir))
                Directory.Delete(outputDir, true);
        }
    }
}
