TaskType = "Calibrate"

[CalibrationParameters]
WriteIntermediateFiles = false
MinMS1IsotopicPeaksNeededForConfirmedIdentification = 3
MinMS2IsotopicPeaksNeededForConfirmedIdentification = 2
NumFragmentsNeededForEveryIdentification = 10

[CommonParameters]
MaxParallelFilesToAnalyze = 1
MaxThreadsToUsePerFile = 7
LocalizeAll = true
ListOfModsFixed = "Common Fixed\tCarbamidomethyl of C"
ListOfModsVariable = "Common Variable\tOxidation of M"
DoPrecursorDeconvolution = true
UseProvidedPrecursorInfo = true
DeconvolutionIntensityRatio = 3.0
DeconvolutionMaxAssumedChargeState = 12
DeconvolutionMassTolerance = "±4.0000 PPM"
TotalPartitions = 1
BIons = true
YIons = true
ZdotIons = false
CIons = false
ProductMassTolerance = "±25.0000 PPM"
PrecursorMassTolerance = "±15.0000 PPM"
ConserveMemory = true
ScoreCutoff = 5.0
ReportAllAmbiguity = true
ExcelCompatible = true
TopNpeaks = 200
MinRatio = 0.01
TrimMs1Peaks = false
TrimMsMsPeaks = true
TaskDescriptor = "CalibrateTask"
CalculateEValue = false

[CommonParameters.DigestionParams]
MaxMissedCleavages = 2
InitiatorMethionineBehavior = "Variable"
MinPeptideLength = 6
MaxPeptideLength = 50
MaxModificationIsoforms = 1024
MaxModsForPeptide = 3
Protease = "trypsin"
