TaskType = "Search"

[SearchParameters]
DisposeOfFileWhenDone = true
AddCompIons = true
DoParsimony = false
ModPeptidesAreUnique = true
NoOneHitWonders = false
MatchBetweenRuns = false
QuantifyPpmTol = 5.0
DoHistogramAnalysis = false
SearchTarget = true
DecoyType = "None"
MassDiffAcceptorType = "Open"
WritePrunedDatabase = false
KeepAllUniprotMods = true
DoLocalizationAnalysis = true
DoQuantification = false
SearchType = "Modern"
MaxFragmentSize = 30000.0
HistogramBinTolInDaltons = 0.003
MaximumMassThatFragmentIonScoreIsDoubled = 600.0

[SearchParameters.ModsToWriteSelection]
ProteinTermMod = 3
UniProt = 2

[CommonParameters]
MaxParallelFilesToAnalyze = 1
MaxThreadsToUsePerFile = 7
LocalizeAll = false
ListOfModsFixed = "Common Fixed\tCarbamidomethyl of C"
ListOfModsVariable = ""
ListOfModsLocalize = ""
DoPrecursorDeconvolution = false
UseProvidedPrecursorInfo = true
DeconvolutionIntensityRatio = 3.0
DeconvolutionMaxAssumedChargeState = 12
DeconvolutionMassTolerance = "±4.0000 PPM"
TotalPartitions = 8
BIons = true
YIons = false
ZdotIons = false
CIons = false
ProductMassTolerance = "±23.0000 PPM"
PrecursorMassTolerance = "±5.0000 PPM"
ScoreCutoff = 4.0
ReportAllAmbiguity = false
ExcelCompatible = true
TopNpeaks = 200
MinRatio = 0.01
TrimMs1Peaks = false
TrimMsMsPeaks = true
TaskDescriptor = "SearchTask"
CalculateEValue = false

[CommonParameters.DigestionParams]
MaxMissedCleavages = 2
InitiatorMethionineBehavior = "Variable"
MinPeptideLength = 4
MaxPeptideLength = 20
MaxModificationIsoforms = 1024
MaxModsForPeptide = 3
Protease = "singleN"
SemiProteaseDigestion = false
TerminusTypeSemiProtease = "None"
